name: qml_challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - backports.zstd=1.3.0=py314h680f03e_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py314he701e3d_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py314h909e829_3
  - cycler=0.12.1=pyhcf101f3_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=pyh7db6752_0
  - freetype=2.14.1=h57928b3_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fuzzywuzzy=0.18.0=pyhd8ed1ab_1
  - greenlet=3.3.0=py314h13fbf68_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py314hf309875_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - levenshtein=0.27.3=py314h13fbf68_0
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libboost=1.86.0=h444863b_2
  - libboost-python=1.86.0=py314hbac2fa4_5
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.86.3=h9bccc14_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libmpdec=4.0.0=h827c3e9_0
  - libpng=1.6.54=h7351971_0
  - libpq=18.1=h9e1d4a5_3
  - librdkit=2025.09.4=h0cb3073_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-base=3.10.8=py314hfa45d96_0
  - mkl=2025.3.0=hac47afa_455
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.1=py314h06c3c77_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314hd8fd7ce_2
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pillow=11.3.0=py314hb9a687b_3
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pycairo=1.29.0=py314hc042690_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytdc=0.3.8=pyhd8ed1ab_1
  - python=3.14.2=h3bc0a5a_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-levenshtein=0.27.3=pyh332efcf_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - rapidfuzz=3.14.3=py314h13fbf68_1
  - rdkit=2025.09.4=py314h16c9f8d_0
  - reportlab=4.4.9=py314h5a2d7ad_0
  - requests=2.32.5=pyhcf101f3_1
  - rlpycairo=0.4.0=pyh6c17108_0
  - scikit-learn=1.8.0=np2py314h1b5b07a_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.45=py314h5a2d7ad_0
  - sqlite=3.51.1=hda9a48d_0
  - statsmodels=0.14.6=py314h2dcd201_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py314h5a2d7ad_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - appdirs==1.4.4
      - astunparse==1.6.3
      - autograd==1.8.0
      - autoray==0.8.2
      - cachetools==6.2.4
      - diastatic-malt==2.15.2
      - gast==0.7.0
      - pennylane==0.44.0
      - pennylane-lightning==0.44.0
      - rustworkx==0.17.1
      - scipy==1.17.0
      - scipy-openblas32==0.3.30.443.1
      - termcolor==3.3.0
      - tomlkit==0.14.0
      - wheel==0.45.1
prefix: C:\Users\cvetk\miniconda3\envs\qml_challenge
